language: ruby
rvm:
  # The version used at SLE12
  - 2.1.2

  # The version used at openSUSE 13.2
  - 2.1.3

  # Other Ruby Versions
  - 2.1.10
  - 2.2.4
  - 2.3.0

  # Future versions
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - |
    bash -c " # Install MariaDB
    sudo bash .travis_mariadb.sh
    "

before_script:
  - mysql -e 'create database portus_test;'

script:
  - bundle exec rspec spec packaging/suse/portusctl/spec
  - bundle exec rubocop -V
  - bundle exec rubocop -F
  - bundle exec brakeman -z -A -x CheckUnscopedFind,CheckRender

env:
  global:
  # OSC_CREDENTIALS are kept secret
  # In order to update them, run:
  #   travis encrypt OSC_CREDENTIALS=user:password
  # more info at: http://docs.travis-ci.com/user/environment-variables/#Secure-Variables
  - OBS_REPO=Virtualization:containers:Portus
  - OBS_BRANCH=master
  - secure: "Umlxpe6wARqVCB4MmQj9MpjGy7Q8odYEohwi4kxOj2hp/uCrqrl1HIoAd7mgB0ylpcbri5HVuBg4EpBoT5VC4NYILnSRPxr3dvHcsK8K7ZO3fuxHnQ666s8P19NSVmDf+K0mlHKv5J6dKIPTFIO1e1Ynbbj97CPo4b2mUJjPq/g="

after_success:
  - packaging/suse/package_and_push_to_obs.sh

addons:
  code_climate:
    repo_token: 18a0cf6c35e0c801678f12f444051c33e0390ce0efa91ec06a2aa5068b10c19e
