language: ruby
sudo: required
dist: trusty
rvm:
  - 2.5.0
cache: bundler

install:
  - chmod +x bin/ci/install.sh && ./bin/ci/install.sh

before_script:
  - chmod +x bin/ci/before_script.sh && ./bin/ci/before_script.sh

script:
  - chmod +x bin/ci/run.sh && ./bin/ci/run.sh

after_script:
  - chmod +x bin/ci/after_script.sh && ./bin/ci/after_script.sh

env:
  global:
    # OSC_CREDENTIALS are kept secret
    # In order to update them, run:
    #   travis encrypt OSC_CREDENTIALS=user:password
    # more info at: http://docs.travis-ci.com/user/environment-variables/#Secure-Variables
    - OBS_REPO=Virtualization:containers:Portus
    - OBS_BRANCH=master
    - secure: "SgH8Wvm6n71GTZqTk2Ww/vLg3KK1QhgBMRSs+85TFemJvUDEWLKtANGI2szlqJOfOEWqHZ4rdzgMamtYfGmOZvjUBebaIXlYMcPyKSmcQZX/80R1/v7KFyhP2vqrb+ok/rK6lLXX06jDhohUS04vnx4i1EtoxH62dKImdlZsjzI="

    # DB options for both adapters and Travis.
    - PORTUS_DB_USERNAME=travis

  matrix:
    - PORTUS_CI=integration PROFILES=clair
    - PORTUS_CI=integration PROFILES=ldap
    - PORTUS_DB_ADAPTER=mysql2 PORTUS_CI=unit
    - PORTUS_DB_ADAPTER=postgresql PORTUS_CI=unit

after_success:
  - packaging/suse/package_and_push_to_obs.sh

addons:
  code_climate:
    repo_token: 18a0cf6c35e0c801678f12f444051c33e0390ce0efa91ec06a2aa5068b10c19e
  mariadb: '10.2'
  postgresql: '9.6'
  chrome: stable
