language: ruby
sudo: required
dist: trusty
rvm:
  - 2.5.0

matrix:
  allow_failures:
    - rvm: ruby-head

cache:
  directories:
    - $PWD/travis_phantomjs

before_install:
  - phantomjs --version
  - export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi
  - if [ $(phantomjs --version) != '2.1.1' ]; then wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi
  - if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi
  - phantomjs --version

  # Use the latest stable Node.js
  - nvm install stable
  - nvm use stable

  # Install Yarn
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo apt-get install yarn
  - yarn install

  # Intall Go, which is needed for git-validation
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.8 bash)"
  - go get -u github.com/vbatts/git-validation

before_script:
  - mysql -e 'create database portus_test;'
  - psql -c 'create database portus_test' -U postgres

script:
  # Compile assets
  - bundle exec rake portus:assets:compile

  # Ruby tests
  - bundle exec rspec spec --tag ~integration

  # Style and security checks
  - bundle exec rubocop -V
  - bundle exec rubocop -F

  # Note: it ignores a couple of files which use ruby 2.5 syntax which brakeman
  # does not know how to handle...
  - bundle exec brakeman --skip-files lib/portus/background/sync.rb,lib/portus/registry_client.rb

  - bundle exec rake portus:annotate_and_exit

  # JavaScript tests
  - yarn test

  # JavaScript style
  - yarn eslint

  # Test commit messages
  - bundle exec rake test:git

env:
  global:
    # OSC_CREDENTIALS are kept secret
    # In order to update them, run:
    #   travis encrypt OSC_CREDENTIALS=user:password
    # more info at: http://docs.travis-ci.com/user/environment-variables/#Secure-Variables
    - OBS_REPO=Virtualization:containers:Portus
    - OBS_BRANCH=master
    - secure: "SgH8Wvm6n71GTZqTk2Ww/vLg3KK1QhgBMRSs+85TFemJvUDEWLKtANGI2szlqJOfOEWqHZ4rdzgMamtYfGmOZvjUBebaIXlYMcPyKSmcQZX/80R1/v7KFyhP2vqrb+ok/rK6lLXX06jDhohUS04vnx4i1EtoxH62dKImdlZsjzI="

    # DB options for both adapters and Travis.
    - PORTUS_DB_USERNAME=travis

  matrix:
    - PORTUS_DB_ADAPTER=mysql2
    - PORTUS_DB_ADAPTER=postgresql

after_success:
  - packaging/suse/package_and_push_to_obs.sh

addons:
  code_climate:
    repo_token: 18a0cf6c35e0c801678f12f444051c33e0390ce0efa91ec06a2aa5068b10c19e
  mariadb: '10.2'
  postgresql: '9.6'
